# 错误处理

js中的错误处理是很多开发者容易忽略的地方。但是现在js应用广泛，要重视起来了。

在公司里面开发大型项目需要了解错误处理的知识。某些大型项目抛出错误方面公司有强制要求

## js 中的错误分为两种：

1. 语法错误：会导致整个脚本块无法执行。```sd{}.23...```。标准见js基本语法（js在执行代码的时候虽然会看一行执行一行，但是在看一行之前会在该脚本块扫一眼有没有语法错误的地方。如果有语法错误，该脚本块所有代码无法执行。）语法错误非常容易发现
2. 运行错误又分为两种：
   1. 运行报错：会导致当前脚本块后续代码无法执行。（若abc未定义，```console.log(abc)```）
   2. 运行结果不符合预期，连错误都不报。最头痛

```js
//运行结果不符合预期举例：实际情况可能更复杂
var a = prompt("请输入第一个数");
var b = prompt("请输入第二个数");
function sum(n1, n2) {
  return n1 + n2;
}
console.log(sum(a, b));
```

### js基本语法

- 语法部分必须都是英文符号
- js 代码由多条语句构成，每个语句用英文分号结束(并非强制要求，但是建议大家书写)
- js 代码从上到下同步执行(上一条语句没有执行完，下一条语句等着)
- js 语言大小写敏感，大小写有不同的含义

## 如何调试错误！

1. 控制台打印，使用广泛
2. 断点调试。控制台第一个符号是运行下一步，第二个符号是进入函数
  1. 控制台调试
  2. vscode插件调试。目前只支持文件调试（更改.vacode文件中的url的端口号）按F5，我的电脑不好使

## 如何抛出错误

抛出错误通常发生在函数的书写中

错误在 js 中的本质上是一个对象，抛出对象的语法为：

```js
throw 错误对象（js不严格要求它是错误对象，字符串等也可）; //错误对象的构造函数为Error，即```throw new Error()```
throw new Error(错误消息是一个字符串，可以传也可以不传)
```

错误对象的构造函数为Error。

Error构造函数还提供了一些其他可以抛出的错误对象。
  - 如：RangeError（数组参数超出有效范围）等。见Error MDN
  - ReferenceError：表示无效引用。```throw new ReferenceError("de")```
  - SyntaxError：语法错误
  - TypeError：类型错误。最常见

```js
//错误堆栈的形成：C中断--B中断--A中断--window全局环境中断
//了解错误是怎么一层一层出来的
function A() {
  B();
  console.log("A");//执行不了
}
function B() {
  C();
  console.log("B");//执行不了
}
function C() {
  throw new Error("fjsef");
}
A();
console.log("G");//执行不了
```

### error对象里面可以访问的属性

```js
var e = new Error("fefwe");
console.log(e);//看不出对象的内部结构
console.dir(e);//该方法可以查看对象的内部结构。发现error对象的属性message和stack
```

- message属性：表示错误信息，即我们赋的值
- stack属性：表示错误堆栈


## 如何捕获错误

捕获错误：调用函数的时候告诉你发生了什么问题，发生错误的时候我要做什么处理

即希望实现：当发生某个错误的时候，程序应该做什么处理

捕获错误和调试错误有区别（有的错误比如断网的错误，程序是没有问题的，但是错误无法避免并且无法消灭，我们只需要捕获错误并作出相应处理即可）

捕获错误的完整语法如下：

```js
try {
  //代码块1
} catch (错误对象) {
  //代码块2。执行的对象就是try里面的错误对象
} finally {
  //代码块3
}
```
```js
function A() {
  try {
    console.log(a);//a未定义
  } catch (err) {
    console.log("生生了错误", err);
    return 3;
  } finally {
    console.log("运行结束");
    return 4
  }
}
console.log(A());//4。若finally里面没有return 4，则最终结果也不是undefined，而是3
```
上方代码块的意思是：当运行代码块 1 时，如果发生错误，立即停止代码 1 的执行，转而执行代码 2，错误对象为抛出的错误对象。无论代码 1 和代码 2 是否执行，最终都将执行代码 3！

- 若没有错误不会执行catch。即使catch里面写了return也一定会执行finally
- finally可以省略，catch也可以省略。

```js
function A() {
  B();
  console.log("A");
}
function B() {
  // C();
  // console.log("B");
  try {
    C();
    console.log("B");
  } catch (err) {
    console.log("运行函数C的时候发生了问题", err);
  } finally {
    console.log("处理完成");
  } //捕获错误并处理。（此时的错误堆栈：C-->B捕获并处理，-->A-->Global）错误堆栈的处理顺序不变，但是对后续函数的影响变了
}
function C() {
  throw new Error("fjei");
}
A();
console.log("Global");
```


js基础部分已经全部结束。会用js语言说话了。相当于要上大学了

接下来要学习在浏览器环境里面有哪些东西可以用。与标准库的学习类似

不要着急啊，一定要把基础打牢之后再向后继续学习。加油！